### ISSUE TITLE
ENH: Support BSEuropeanBinaryOption put

### ISSUE THREAD

**Issue by simaki** [pfnet-research/pfhedge#105]
```py
from pfhedge.nn import BSEuropeanBinaryOption

m = BSEuropeanBinaryOption(call=False)
```

```
Traceback (most recent call last):     
  File "/private/tmp/tmp.py", line 3, in <module>
    m = BSEuropeanBinaryOption(call=False)
  File "/usr/local/lib/python3.9/site-packages/pfhedge/nn/modules/bs/european_binary.py", line 49, in __init__
    raise ValueError(
ValueError: BSEuropeanBinaryOption for a put option is not yet supported.
```

**Comment by simaki** [comment]
resolved
